# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'm3helper/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(329, 299)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rc/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_anim_dump = QtWidgets.QPushButton(self.groupBox)
        self.btn_anim_dump.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_anim_dump.setAcceptDrops(True)
        self.btn_anim_dump.setObjectName("btn_anim_dump")
        self.verticalLayout.addWidget(self.btn_anim_dump)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbx_auto_copy = QtWidgets.QCheckBox(self.groupBox)
        self.cbx_auto_copy.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbx_auto_copy.setObjectName("cbx_auto_copy")
        self.horizontalLayout.addWidget(self.cbx_auto_copy)
        self.ed_target_dir = QtWidgets.QLineEdit(self.groupBox)
        self.ed_target_dir.setReadOnly(True)
        self.ed_target_dir.setObjectName("ed_target_dir")
        self.horizontalLayout.addWidget(self.ed_target_dir)
        self.btn_select_dir = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_dir.setObjectName("btn_select_dir")
        self.horizontalLayout.addWidget(self.btn_select_dir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.ed_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ed_log.setReadOnly(True)
        self.ed_log.setObjectName("ed_log")
        self.gridLayout.addWidget(self.ed_log, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 329, 25))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuAction = QtWidgets.QMenu(self.menuBar)
        self.menuAction.setObjectName("menuAction")
        MainWindow.setMenuBar(self.menuBar)
        self.actionT = QtWidgets.QAction(MainWindow)
        self.actionT.setObjectName("actionT")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionClearLog = QtWidgets.QAction(MainWindow)
        self.actionClearLog.setObjectName("actionClearLog")
        self.menuMenu.addAction(self.actionSettings)
        self.menuMenu.addAction(self.actionAbout)
        self.menuMenu.addAction(self.actionQuit)
        self.menuAction.addAction(self.actionClearLog)
        self.menuBar.addAction(self.menuMenu.menuAction())
        self.menuBar.addAction(self.menuAction.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "m3helper"))
        self.groupBox.setTitle(_translate("MainWindow", "Textures finder"))
        self.btn_anim_dump.setText(_translate("MainWindow", "Open / Drop M3"))
        self.cbx_auto_copy.setToolTip(_translate("MainWindow", "Automatically copy model textures to selected directory."))
        self.cbx_auto_copy.setText(_translate("MainWindow", "Copy to"))
        self.btn_select_dir.setText(_translate("MainWindow", "Browse"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuAction.setTitle(_translate("MainWindow", "Action"))
        self.actionT.setText(_translate("MainWindow", "t"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionClearLog.setText(_translate("MainWindow", "Clear log"))

from .rc_rc import *
